version: '3.4'

services:
  catalogdb:
    image: mongo
  
  catelog.api:
    image: ${DOCKER_REGISTRY-}catelog
    build:
      context: .
      dockerfile: Catelog.API/Dockerfile

volumes:
  mongo_data: